# Kickstarter Prediction with Model v1

In [1]:
#Import libraries 
import pandas as pd
import numpy as np
from pickle import load
import tensorflow as tf
from tensorflow import keras
import os

### Define the dummy input as a dictionary

In [2]:
dummy_input = {
  "main_category": "Publishing",
  "country": "US",
  "usd_goal_real": 50000.00,
  "period": 34
}

In [3]:
# Define in a list the categories for prediction diccionary
country_categories = ['country_GB', 'country_Other', 'country_US']
main_categories = [
    'main_category_Art',
    'main_category_Comics',
    'main_category_Crafts',
    'main_category_Dance',
    'main_category_Design',
    'main_category_Fashion',
    'main_category_Film & Video',
    'main_category_Food',
    'main_category_Games',
    'main_category_Journalism',
    'main_category_Music',
    'main_category_Photography',
    'main_category_Publishing',
    'main_category_Technology',
    'main_category_Theater'
]

In [4]:
def one_hot_encoding(raw_prediction_input, categorical_list, category_key):
    res = [i for i in categorical_list if raw_prediction_input[category_key] in i]
    print(res)
    for i in categorical_list:
        raw_prediction_input[i] = 0
    raw_prediction_input[res[0]] = 1
    del raw_prediction_input[category_key]
    return raw_prediction_input

In [5]:
country_one_hot_input = one_hot_encoding(dummy_input, country_categories, 'country')
complete_one_hot_input = one_hot_encoding(dummy_input, main_categories, 'main_category')

['country_US']
['main_category_Publishing']


In [6]:
# Transform diccionary to list 
to_predict_input_list = []
for key, value in complete_one_hot_input.items():
    temp = value
    to_predict_input_list.append(temp)
to_predict_input_list

[50000.0, 34, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

### Load scaler

In [8]:
scaler = load(open('scaler_kickstarter_v4.pkl', 'rb'))

In [9]:
to_predict_input_array = np.array([to_predict_input_list])
to_predict_input_array

array([[5.0e+04, 3.4e+01, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00]])

In [10]:
standardized_input_array = scaler.transform(to_predict_input_array)
standardized_input_array

array([[ 0.01306033,  0.16203608, -0.31643483, -0.37326324,  0.52071169,
        -0.28996706, -0.18227229, -0.15027646, -0.10889338, -0.29529599,
        -0.24527386, -0.449739  , -0.25726268, -0.32357014, -0.10739067,
        -0.40551388, -0.16878094,  2.95170904, -0.29077066, -0.18533849]])

In [11]:
standardized_input_array.shape

(1, 20)

### Load the already trained model v1

In [13]:
new_model = tf.keras.models.load_model('saved_model\kickstarter_v4')

### Predict the input with the trained model

In [14]:
# First value of the array is the probability that will fail
# Second value of the array means the probability to succeed
prediction = new_model.predict(standardized_input_array)
prediction

array([[0.7907903 , 0.20920971]], dtype=float32)

In [15]:
prediction[0,1]

0.20920971